### ISSUE TITLE
It would great if Jenkins endpoints are triggered on certain conditions

### ISSUE THREAD

**Issue by mikolajgasior** [mikolajgasior/buildtrigger#3]
Currently, conditions for triggering Jenkins endpoints are hardcoded. It would be great if these could be defined in the configuration file. Since this is a Go tool then Go templating can be used to define a template that needs to output `1`.

**Comment by nicholasgasior** [comment]
Also, variables like branch or repository name can come from a template.

**Comment by nicholasgasior** [comment]
Let's change conditions like `push: true` to names of certain events - just like on the following example. 
```
events: [{
  "name": "push",
  "conditions": { ... }
}]
```

Getting repository and branch name should be extracted to separate function and it should read specific JSON key based on the event type.

**Comment by nicholasgasior** [comment]
Rename the whole thing to githubwebhook?

**Comment by mikolajgasior** [comment]
Done in gen64/github-webhookd.
